
services:
  redis: 
    image: redis
    ports:
      - "6380:6379"
    networks:
      - net1
    environment:
      - REDIS_CONNECTION=redis:6379
  
  #api:
  #  build:
  #      context: .
  #      dockerfile: "./BookingClone.Api/Dockerfile"
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - redis
  #  networks:
  #    - net1
  #  environment:
  #    - ConnectionStrings__redis=redis:6379
  #    - ConnectionStrings__default=Server.;Integrated Security=True;Database=BookingClone;TrustServerCertificate=True;

networks:
  net1:
    driver: bridge


      
    
  
  
